### ISSUE TITLE
stopPropagation on ESC keypress

### ISSUE THREAD

**Issue by utilmind** [MohammadYounes/AlertifyJS#223] opened 2019-11-20 08:16 UTC
Hello! I already requested before the feature, noPropagateClicks: https://github.com/MohammadYounes/AlertifyJS/issues/216

@MohammadYounes has suggested to hook the instance.elements.root.onclick event and stop propagation of all clicks. I'm doing so, this is solved that problem, thanks!

However. now I would like to have something like noPropagageKeypresses. Particularly I need toinstance.elements.root.onclick stop propagation of ESC keypress.

I'm using Bootstrap 4 modal dialog boxes and sometimes can display alert() or confirm() over the Bootstrap's modal. If ESC key will be pressed the dialog under the Alertify will be closed too, reacting on ESC keypress.

I have already tried to override "instance.elements.root.onkeyup". I'm watching the keycodes and stopping the event propagation in case of ESC keypress. However, this made confirm() dialogs to stop working properly. confirm()'s doesn't triggers onCancel event after ESC keypress.

Question: is there way to stop propagation of keypreses (no matter, certain key like ESC, or all keys), but still have the confirm() which works properly and triggers onCancel event on ESC?

Currently I have modified the "alertify.js" and added event.stopPropagation between the following lines:
```
if (instance.__internal.buttons.length === 0 && keyCode === keys.ESC && instance.get('closable') === true) {
    event.stopPropagation(); // inserted line of code
    triggerClose(instance);

```

**Comment by MohammadYounes** [comment] 2019-11-20 10:40
You need to stop the propagation on key down :

```js
alertify.defaults.hooks.postinit = function(instance){
  instance.elements.root.onkeydown = function(e){
   if(e.keyCode == 27) e.stopPropagation()
  }
}
```

**Comment by utilmind** [comment] 2019-11-20 21:33
Thanks for response! I have tried it already. Except only that I have hooked onKeyUp event instead of onKeyDown, but result is the same.

The Alertify box is the first (topmost) element which receives ESC key, closing itself gracefully, but then still propagating the keypress to another controls.

Here is the test playground which reproduces the possible(?) bug:
http://utilmind.com/demos/2019/bug-reproducing-alertify-1-12/

You may also download ZIPped example to test locally, from http://utilmind.com/demos/2019/bug-reproducing-alertify-1-12/bug-reproducing-alertify-1-12.zip

**Comment by MohammadYounes** [comment] 2019-11-21 10:29
@utilmind This is caused by another code block in your page that is listening to `keyup` event on `window`  object. 

You can do the following trick:

```js
alertify.defaults.hooks.postinit = function(instance){
  instance.elements.root.onkeydown = function(e){
   if(e.keyCode == 27) e.stopPropagation()
  }
  instance.elements.root.onkeyup = function(e){
   if(e.keyCode == 27) e.__ignore = true
  }
}
```
Then wrap your code block with a condition to check if it should ignore closing the modal:

```js
$(window).keyup(function(e) {
   if(!e.originalEvent.__ignore){
        // do your thing...
   }
}
```
Thanks.

**Closed by MohammadYounes** 2019-11-21 10:29 UTC
Labels: question

**Comment by utilmind** [comment] 2019-11-22 03:41
Thanks for your help! Unfortunately this didn't worked either, but I have managed to prevent Bootstrap modal different way.

I have prepared the demo of solution of this issue in case if someone will have the same problem with Alertify together with Boostrap modal in future:
https://jsfiddle.net/utilmind/pz678uv9/

**Comment by MohammadYounes** [comment] 2019-11-22 11:07
@utilmind Are you sure it didn't work ? see https://jsfiddle.net/n0wxmrpj/
